version: '3.5'

services: 
    database:
        image: mysql:latest
        container_name: meu-mysql
        
        ports:
            - 3306:3306
            
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root

            